name: Nightly

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: nightly-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      signing: self-signed
      artifact-prefix: open-x3d-pro-nightly
